/-
Copyright (c) 2026 Weixuan Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Weixuan Yuan
-/
import GraphLib.Graph.Delete
import GraphLib.Graph.Map
import GraphLib.Walk.Cycle

/-!
# General undirected walk realization

Realization checks each reconstructed full `Edge`, never its raw tag alone.
-/

namespace GraphLib

variable {α β γ δ : Type*}

open scoped GraphLib

namespace Graph

/-- A raw general walk realized in an undirected graph. -/
inductive IsWalkIn (G : Graph α β) : Walk α β → Prop
  | singleton (v : α) (hv : v ∈ V(G)) : G.IsWalkIn (.singleton v)
  | cons (w : Walk α β) (v : α) (t : β) (hw : G.IsWalkIn w)
      (hlink : G.IsLink ⟨t, s(w.tail, v)⟩ w.tail v) : G.IsWalkIn (w.cons v t)

namespace IsWalkIn

@[simp] theorem singleton_iff (G : Graph α β) (v : α) :
    G.IsWalkIn (.singleton v) ↔ v ∈ V(G) := by
  constructor
  · intro h
    cases h
    assumption
  · exact .singleton v

@[simp] theorem cons_iff (G : Graph α β) (w : Walk α β) (v : α) (t : β) :
    G.IsWalkIn (w.cons v t) ↔
      G.IsWalkIn w ∧ G.IsLink ⟨t, s(w.tail, v)⟩ w.tail v := by
  constructor
  · intro h
    cases h with
    | cons _ _ _ hw he => exact ⟨hw, he⟩
  · rintro ⟨hw, he⟩
    exact .cons w v t hw he

theorem head_mem {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) : w.head ∈ V(G) := by
  induction h with
  | singleton v hv => exact hv
  | cons w v t hw he ih => exact ih

theorem tail_mem {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) : w.tail ∈ V(G) := by
  cases h with
  | singleton v hv => exact hv
  | cons w v t hw he => exact he.right_mem

theorem vertex_mem {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w)
    {v : α} (hv : v ∈ w.vertices) : v ∈ V(G) := by
  induction h with
  | singleton u hu =>
      simp only [Walk.vertices_singleton, List.mem_singleton] at hv
      exact hv ▸ hu
  | cons w u t hw he ih =>
      simp only [Walk.vertices_cons, List.concat_eq_append, List.mem_append,
        List.mem_singleton] at hv
      rcases hv with hv | rfl
      · exact ih hv
      · exact he.right_mem

theorem edge_mem {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w)
    {e : Edge α β} (he : e ∈ w.edges) : e ∈ E(G) := by
  induction h with
  | singleton v hv => simp at he
  | cons w v t hw hlink ih =>
      simp only [Walk.edges_cons, List.concat_eq_append, List.mem_append,
        List.mem_singleton] at he
      rcases he with he | rfl
      · exact ih he
      · exact hlink.edge_mem

/-- Realization is exactly head membership plus membership of all reconstructed actual edges. -/
theorem iff_edges (G : Graph α β) (w : Walk α β) :
    G.IsWalkIn w ↔ w.head ∈ V(G) ∧ ∀ e ∈ w.edges, e ∈ E(G) := by
  constructor
  · intro h
    exact ⟨h.head_mem, fun _ he => h.edge_mem he⟩
  · rintro ⟨hhead, hedges⟩
    induction w with
    | singleton v => exact .singleton v hhead
    | cons w v t ih =>
        have hprefix : ∀ e ∈ w.edges, e ∈ E(G) := by
          intro e he
          exact hedges e (by simp [Walk.edges, List.concat_eq_append, he])
        have hw := ih hhead hprefix
        have hlast : Edge.mk t s(w.tail, v) ∈ E(G) :=
          hedges _ (by simp [Walk.edges, List.concat_eq_append])
        exact .cons w v t hw ⟨hlast, rfl⟩

/-- Realization depends only on the ambient vertex and actual-edge sets. -/
theorem congr {G H : Graph α β} {w : Walk α β}
    (hV : V(G) = V(H)) (hE : E(G) = E(H)) : G.IsWalkIn w ↔ H.IsWalkIn w := by
  rw [iff_edges G w, iff_edges H w, hV, hE]

/-- Realization is monotone under the subgraph order. -/
theorem mono {G H : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) (hGH : G ≤ H) :
    H.IsWalkIn w := by
  rw [IsWalkIn.iff_edges H w]
  exact ⟨hGH.vertexSet_subset h.head_mem,
    fun _ he => hGH.edgeSet_subset (h.edge_mem he)⟩

/-- The graph generated by a realized walk is a subgraph of the ambient graph. -/
theorem toGraph_le {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) : w.toGraph ≤ G :=
  ⟨fun _ hv => h.vertex_mem hv, fun _ he => h.edge_mem he⟩

/-- A walk is realized whenever its generated graph is a subgraph. -/
theorem of_toGraph_le (G : Graph α β) (w : Walk α β) (h : w.toGraph ≤ G) :
    G.IsWalkIn w := by
  rw [IsWalkIn.iff_edges G w]
  exact ⟨h.vertexSet_subset (by exact w.head_mem),
    fun _ he => h.edgeSet_subset he⟩

theorem iff_toGraph_le (G : Graph α β) (w : Walk α β) :
    G.IsWalkIn w ↔ w.toGraph ≤ G :=
  ⟨toGraph_le, IsWalkIn.of_toGraph_le G w⟩

/-- Undirected reversal remains realized in the same graph. -/
theorem reverse {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) :
    G.IsWalkIn w.reverse := by
  rw [IsWalkIn.iff_edges G w.reverse]
  refine ⟨by simpa using h.tail_mem, ?_⟩
  intro e he
  rw [Walk.edges_reverse] at he
  exact h.edge_mem (List.mem_reverse.mp he)

/-- Dropping the final step preserves realization. -/
theorem dropTail {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) :
    G.IsWalkIn w.dropTail := by
  cases h with
  | singleton v hv => exact .singleton v hv
  | cons w v t hw hlink => exact hw

/-- Dropping the initial step preserves realization. -/
theorem dropHead {G : Graph α β} {w : Walk α β} (h : G.IsWalkIn w) :
    G.IsWalkIn w.dropHead := by
  induction h with
  | singleton v hv => exact .singleton v hv
  | cons w v t hw hlink ih =>
      cases w with
      | singleton u => exact .singleton v hlink.right_mem
      | cons q u s =>
          apply Graph.IsWalkIn.cons (Walk.dropHead (q.cons u s)) v t ih
          simpa using hlink

/-- A realized prefix is realized. -/
theorem prefixUntil [DecidableEq α] {G : Graph α β} {w : Walk α β}
    (h : G.IsWalkIn w) (v : α) (hv : v ∈ w) : G.IsWalkIn (w.prefixUntil v hv) := by
  rw [iff_edges]
  exact ⟨by simpa using h.head_mem,
    fun _ he => h.edge_mem (Walk.edges_prefixUntil_subset w v hv he)⟩

/-- A realized suffix is realized. -/
theorem suffixFrom [DecidableEq α] {G : Graph α β} {w : Walk α β}
    (h : G.IsWalkIn w) (v : α) (hv : v ∈ w) : G.IsWalkIn (w.suffixFrom v hv) := by
  rw [iff_edges]
  exact ⟨by simpa using h.vertex_mem (show v ∈ w.vertices from hv),
    fun _ he => h.edge_mem (Walk.edges_suffixFrom_subset w v hv he)⟩

/-- Erasing cycles from a realized walk preserves realization. -/
theorem cycleErase [DecidableEq α] {G : Graph α β} {w : Walk α β}
    (h : G.IsWalkIn w) : G.IsWalkIn w.cycleErase := by
  fun_induction Walk.cycleErase w with
  | case1 => exact h
  | case2 w v t hv ih =>
      exact ih ((Graph.IsWalkIn.dropTail h).prefixUntil v hv)
  | case3 w v t hv ih =>
      cases h with
      | cons _ _ _ hw hlink =>
          exact .cons _ _ _ (ih hw) (by simpa using hlink)

/-- Join two realized walks with a realized bridge edge. -/
theorem append {G : Graph α β} {p q : Walk α β} (hp : G.IsWalkIn p)
    (hq : G.IsWalkIn q) (t : β)
    (hbridge : G.IsLink ⟨t, s(p.tail, q.head)⟩ p.tail q.head) :
    G.IsWalkIn (p.append q t) := by
  induction hq with
  | singleton v hv => exact .cons p v t hp hbridge
  | cons q v s hq hlast ih =>
      exact .cons (p.append q t) v s (ih hbridge) (by simpa using hlast)

/-- Glue two realized walks at a common endpoint without adding a step. -/
theorem glue {G : Graph α β} {p q : Walk α β} (hp : G.IsWalkIn p)
    (hq : G.IsWalkIn q) (hends : p.tail = q.head) : G.IsWalkIn (p.glue q hends) := by
  cases hp with
  | singleton v hv => simpa [Walk.glue] using hq
  | cons p v t hp hlast =>
      apply append hp hq t
      have hvq : v = q.head := by simpa using hends
      simpa [hvq] using hlast

/-- Realization in an induced graph is realization in the ambient graph plus vertex inclusion. -/
theorem induce_iff (G : Graph α β) (S : Set α) (w : Walk α β) :
    (G.induce S).IsWalkIn w ↔ G.IsWalkIn w ∧ ∀ v ∈ w.vertices, v ∈ S := by
  constructor
  · intro h
    exact ⟨h.mono (G.induce_le S), fun v hv =>
      ((G.mem_vertexSet_induce S v).1 (h.vertex_mem hv)).1⟩
  · rintro ⟨hG, hS⟩
    rw [IsWalkIn.iff_edges (G.induce S) w]
    refine ⟨(G.mem_vertexSet_induce S w.head).2 ⟨hS _ w.head_mem, hG.head_mem⟩, ?_⟩
    intro e he
    rw [G.mem_edgeSet_induce]
    refine ⟨hG.edge_mem he, ?_⟩
    intro v hv
    exact hS v (w.toGraph.endpoints_mem e he v hv)

/-- Restricting actual edges preserves exactly the walks whose reconstructed edges survive. -/
theorem restrictEdges_iff (G : Graph α β) (F : Set (Edge α β)) (w : Walk α β) :
    (G.restrictEdges F).IsWalkIn w ↔ G.IsWalkIn w ∧ ∀ e ∈ w.edges, e ∈ F := by
  simp only [iff_edges, G.mem_vertexSet_restrictEdges, G.mem_edgeSet_restrictEdges]
  aesop

/-- Deleting actual edges preserves exactly the walks avoiding those edges. -/
theorem deleteEdges_iff (G : Graph α β) (F : Set (Edge α β)) (w : Walk α β) :
    (G.deleteEdges F).IsWalkIn w ↔ G.IsWalkIn w ∧ ∀ e ∈ w.edges, e ∉ F := by
  simp only [iff_edges, G.mem_vertexSet_deleteEdges, G.mem_edgeSet_deleteEdges]
  aesop

/-- Deleting vertices preserves exactly the walks avoiding the deleted set. -/
theorem deleteVerts_iff (G : Graph α β) (S : Set α) (w : Walk α β) :
    (G.deleteVerts S).IsWalkIn w ↔ G.IsWalkIn w ∧ ∀ v ∈ w.vertices, v ∉ S := by
  simpa [Set.mem_compl_iff] using induce_iff G Sᶜ w

/-- Vertex relabeling transports a realized walk by the same equivalence. -/
theorem relabelVertices {G : Graph α β} {w : Walk α β} (f : α ≃ γ)
    (h : G.IsWalkIn w) : (G.relabelVertices f).IsWalkIn (w.mapVertices f) := by
  induction h with
  | singleton v hv => exact Graph.IsWalkIn.singleton (f v) ⟨v, hv, rfl⟩
  | cons w v t hw hlink ih =>
      apply Graph.IsWalkIn.cons (w.mapVertices f) (f v) t ih
      simpa [Edge.relabelVertices] using
        (G.relabelVertices_isLink f ⟨t, s(w.tail, v)⟩ w.tail v).2 hlink

/-- Tag relabeling transports a realized walk by the same equivalence. -/
theorem relabelTags {G : Graph α β} {w : Walk α β} (g : β ≃ δ)
    (h : G.IsWalkIn w) : (G.relabelTags g).IsWalkIn (w.mapTags g) := by
  induction h with
  | singleton v hv => exact Graph.IsWalkIn.singleton v (by simpa using hv)
  | cons w v t hw hlink ih =>
      apply Graph.IsWalkIn.cons (w.mapTags g) v (g t) ih
      simpa [Edge.relabelTags] using
        (G.relabelTags_isLink g ⟨t, s(w.tail, v)⟩ w.tail v).2 hlink

end IsWalkIn

/-- An undirected trail realized in `G`. -/
def IsTrailIn (G : Graph α β) (t : Trail α β) : Prop := G.IsWalkIn t.val

/-- A path realized in `G`. -/
def IsPathIn (G : Graph α β) (p : Path α β) : Prop := G.IsWalkIn p.val

/-- A circuit realized in `G`. -/
def IsCircuitIn (G : Graph α β) (c : Circuit α β) : Prop := G.IsTrailIn c.val

/-- A cycle realized in `G`. -/
def IsCycleIn (G : Graph α β) (c : Cycle α β) : Prop := G.IsWalkIn c.val

namespace IsTrailIn
theorem isWalkIn {G : Graph α β} {t : Trail α β} (h : G.IsTrailIn t) : G.IsWalkIn t.val := h
theorem reverse {G : Graph α β} {t : Trail α β} (h : G.IsTrailIn t) :
    G.IsTrailIn t.reverse := Graph.IsWalkIn.reverse h
end IsTrailIn

namespace IsPathIn
theorem isWalkIn {G : Graph α β} {p : Path α β} (h : G.IsPathIn p) : G.IsWalkIn p.val := h
theorem reverse {G : Graph α β} {p : Path α β} (h : G.IsPathIn p) :
    G.IsPathIn p.reverse := Graph.IsWalkIn.reverse h
theorem mono {G H : Graph α β} {p : Path α β} (h : G.IsPathIn p) (hGH : G ≤ H) :
    H.IsPathIn p := Graph.IsWalkIn.mono h hGH
theorem edge_mem {G : Graph α β} {p : Path α β} (h : G.IsPathIn p)
    {e : Edge α β} (he : e ∈ p.edges) : e ∈ E(G) := Graph.IsWalkIn.edge_mem h he
theorem glue {G : Graph α β} {p q : Path α β} (hp : G.IsPathIn p)
    (hq : G.IsPathIn q) (hends : p.tail = q.head)
    (hdisj : ∀ v ∈ p.vertices.dropLast, v ∈ q.vertices → False) :
    G.IsPathIn (p.glue q hends hdisj) := Graph.IsWalkIn.glue hp hq hends
theorem induce_iff (G : Graph α β) (S : Set α) (p : Path α β) :
    (G.induce S).IsPathIn p ↔ G.IsPathIn p ∧ ∀ v ∈ p.vertices, v ∈ S :=
  Graph.IsWalkIn.induce_iff G S p.val
theorem restrictEdges_iff (G : Graph α β) (F : Set (Edge α β)) (p : Path α β) :
    (G.restrictEdges F).IsPathIn p ↔ G.IsPathIn p ∧ ∀ e ∈ p.edges, e ∈ F :=
  Graph.IsWalkIn.restrictEdges_iff G F p.val
theorem deleteEdges_iff (G : Graph α β) (F : Set (Edge α β)) (p : Path α β) :
    (G.deleteEdges F).IsPathIn p ↔ G.IsPathIn p ∧ ∀ e ∈ p.edges, e ∉ F :=
  Graph.IsWalkIn.deleteEdges_iff G F p.val
theorem relabelVertices {G : Graph α β} {p : Path α β} (f : α ≃ γ)
    (h : G.IsPathIn p) : (G.relabelVertices f).IsPathIn (p.relabelVertices f) :=
  Graph.IsWalkIn.relabelVertices f h
theorem relabelTags {G : Graph α β} {p : Path α β} (g : β ≃ δ)
    (h : G.IsPathIn p) : (G.relabelTags g).IsPathIn (p.relabelTags g) :=
  Graph.IsWalkIn.relabelTags g h
end IsPathIn

namespace IsCircuitIn
theorem isTrailIn {G : Graph α β} {c : Circuit α β} (h : G.IsCircuitIn c) :
    G.IsTrailIn c.val := h
theorem reverse {G : Graph α β} {c : Circuit α β} (h : G.IsCircuitIn c) :
    G.IsCircuitIn c.reverse := Graph.IsTrailIn.reverse h
end IsCircuitIn

namespace IsCycleIn
theorem isWalkIn {G : Graph α β} {c : Cycle α β} (h : G.IsCycleIn c) :
    G.IsWalkIn c.val := h
theorem reverse {G : Graph α β} {c : Cycle α β} (h : G.IsCycleIn c) :
    G.IsCycleIn c.reverse := Graph.IsWalkIn.reverse h
theorem mono {G H : Graph α β} {c : Cycle α β} (h : G.IsCycleIn c) (hGH : G ≤ H) :
    H.IsCycleIn c := Graph.IsWalkIn.mono h hGH
theorem edge_mem {G : Graph α β} {c : Cycle α β} (h : G.IsCycleIn c)
    {e : Edge α β} (he : e ∈ c.edges) : e ∈ E(G) := Graph.IsWalkIn.edge_mem h he
theorem induce_iff (G : Graph α β) (S : Set α) (c : Cycle α β) :
    (G.induce S).IsCycleIn c ↔ G.IsCycleIn c ∧ ∀ v ∈ c.vertices, v ∈ S :=
  Graph.IsWalkIn.induce_iff G S c.val
theorem restrictEdges_iff (G : Graph α β) (F : Set (Edge α β)) (c : Cycle α β) :
    (G.restrictEdges F).IsCycleIn c ↔ G.IsCycleIn c ∧ ∀ e ∈ c.edges, e ∈ F :=
  Graph.IsWalkIn.restrictEdges_iff G F c.val
theorem deleteEdges_iff (G : Graph α β) (F : Set (Edge α β)) (c : Cycle α β) :
    (G.deleteEdges F).IsCycleIn c ↔ G.IsCycleIn c ∧ ∀ e ∈ c.edges, e ∉ F :=
  Graph.IsWalkIn.deleteEdges_iff G F c.val
theorem relabelVertices {G : Graph α β} {c : Cycle α β} (f : α ≃ γ)
    (h : G.IsCycleIn c) : (G.relabelVertices f).IsCycleIn (c.relabelVertices f) :=
  Graph.IsWalkIn.relabelVertices f h
theorem relabelTags {G : Graph α β} {c : Cycle α β} (g : β ≃ δ)
    (h : G.IsCycleIn c) : (G.relabelTags g).IsCycleIn (c.relabelTags g) :=
  Graph.IsWalkIn.relabelTags g h
end IsCycleIn

end Graph

end GraphLib
