/-
Copyright (c) 2026 Weixuan Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Weixuan Yuan
-/
import GraphLib.Walk.InSimpleDiGraph.VertexSeq
import GraphLib.Walk.SimpleWalk

/-!
# Simple walks realized in simple directed graphs
-/

namespace GraphLib

variable {α γ : Type*}

open scoped GraphLib

namespace SimpleDiGraph

/-! ## Simple walks realized in a simple directed graph -/

/-- A simple walk is realized in `G` when its underlying vertex sequence is
realized in `G`. -/
@[grind] def IsSimpleWalkIn (G : SimpleDiGraph α) (w : SimpleWalk α) : Prop :=
  G.IsVertexSeqIn w.val

namespace IsSimpleWalkIn

/-! ## Bridge to `IsVertexSeqIn` -/

/-- Realization of a simple walk is realization of its underlying vertex
sequence. -/
@[simp, grind =] lemma iff_isVertexSeqIn
    (G : SimpleDiGraph α) (w : SimpleWalk α) :
    G.IsSimpleWalkIn w ↔ G.IsVertexSeqIn w.val := Iff.rfl

/-! ## Vertex membership -/

/-- The head of a realized walk is a vertex of `G`. -/
@[grind →] lemma head_mem (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : w.head ∈ V(G) :=
  IsVertexSeqIn.head_mem G hw

/-- The tail of a realized walk is a vertex of `G`. -/
@[grind →] lemma tail_mem (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : w.tail ∈ V(G) :=
  IsVertexSeqIn.tail_mem G hw

/-- Every vertex visited by a realized walk is a vertex of `G`. -/
@[grind →] lemma mem_vertexSet (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : ∀ v ∈ w.support, v ∈ V(G) :=
  IsVertexSeqIn.mem_vertexSet G hw

/-! ## Vertex and arc membership -/

/-- Any arc traversed by a realized walk is an edge of `G`. -/
@[grind →] lemma arc_mem (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) {a : α × α} (ha : a ∈ w.arcs) : a ∈ E(G) :=
  IsVertexSeqIn.arc_mem G hw ha

/-- A walk is realized in `G` exactly when its head is a vertex of `G` and every
arc it traverses is an edge of `G`. -/
theorem iff_arcs (G : SimpleDiGraph α) (w : SimpleWalk α) :
    G.IsSimpleWalkIn w ↔ w.head ∈ V(G) ∧ ∀ a ∈ w.arcs, a ∈ E(G) :=
  IsVertexSeqIn.iff_arcs G w.val

/-- Realization depends only on the ambient vertex and arc sets. -/
theorem congr {G H : SimpleDiGraph α} {w : SimpleWalk α}
    (hV : V(G) = V(H)) (hE : E(G) = E(H)) :
    G.IsSimpleWalkIn w ↔ H.IsSimpleWalkIn w := by
  rw [iff_arcs G w, iff_arcs H w, hV, hE]

/-! ## Graph transformations -/

theorem induce_iff (G : SimpleDiGraph α) (S : Set α) (w : SimpleWalk α) :
    (G.induce S).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ v ∈ w.support, v ∈ S :=
  IsVertexSeqIn.induce_iff G S w.val

theorem restrictEdges_iff (G : SimpleDiGraph α) (F : Set (α × α)) (w : SimpleWalk α) :
    (G.restrictEdges F).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ a ∈ w.arcs, a ∈ F :=
  IsVertexSeqIn.restrictEdges_iff G F w.val

theorem deleteEdges_iff (G : SimpleDiGraph α) (F : Set (α × α)) (w : SimpleWalk α) :
    (G.deleteEdges F).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ a ∈ w.arcs, a ∉ F :=
  IsVertexSeqIn.deleteEdges_iff G F w.val

theorem deleteVerts_iff (G : SimpleDiGraph α) (S : Set α) (w : SimpleWalk α) :
    (G.deleteVerts S).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ v ∈ w.support, v ∉ S :=
  IsVertexSeqIn.deleteVerts_iff G S w.val

theorem relabelVertices {G : SimpleDiGraph α} {w : SimpleWalk α} (f : α ≃ γ)
    (h : G.IsSimpleWalkIn w) :
    (G.relabelVertices f).IsSimpleWalkIn (SimpleWalk.map f f.injective w) :=
  IsVertexSeqIn.relabelVertices f h

/-- Reversing a realized directed simple walk realizes it in the reversed digraph. -/
theorem reverse (G : SimpleDiGraph α) {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) :
    G.reverse.IsSimpleWalkIn w.reverse :=
  IsVertexSeqIn.reverse G hw

/-! ## Traversed arcs and the generated simple directed graph -/

/-- All arcs traversed by a realized simple walk are edges of `G`, as a bundled
arc-list predicate. -/
lemma arcs_subset_edgeSet (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : ∀ a ∈ w.arcs, a ∈ E(G) :=
  (iff_arcs G w).1 hw |>.2

/-- The simple directed graph generated by a realized simple walk is a subgraph
of `G`. -/
lemma toSimpleDiGraph_le (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : w.toSimpleDiGraph ≤ G := by
  refine ⟨?_, ?_⟩
  · intro v hv
    exact mem_vertexSet G hw v (by simpa using hv)
  · intro a ha
    exact arc_mem G hw (by simpa using ha)

/-- If the simple directed graph generated by a simple walk is a subgraph of
`G`, then the walk is realized in `G`. -/
lemma of_toSimpleDiGraph_le (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hsub : w.toSimpleDiGraph ≤ G) : G.IsSimpleWalkIn w := by
  rw [iff_arcs]
  refine ⟨?_, ?_⟩
  · exact hsub.vertexSet_subset (by simp [SimpleWalk.support])
  · intro a ha
    exact hsub.edgeSet_subset (by simpa using ha)

/-- A simple walk is realized in `G` exactly when its generated simple directed
graph is a subgraph of `G`. -/
theorem iff_toSimpleDiGraph_le (G : SimpleDiGraph α) (w : SimpleWalk α) :
    G.IsSimpleWalkIn w ↔ w.toSimpleDiGraph ≤ G :=
  ⟨toSimpleDiGraph_le G, of_toSimpleDiGraph_le G⟩

/-! ## Closure under walk operations -/

/-- Dropping the last vertex of a realized walk preserves realization. -/
@[grind →] lemma dropTail (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn w.dropTail :=
  IsVertexSeqIn.dropTail G hw

/-- Dropping the first vertex of a realized walk preserves realization. -/
@[grind →] lemma dropHead (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn w.dropHead :=
  IsVertexSeqIn.dropHead G hw

/-- Taking a prefix of a realized walk preserves realization. -/
@[grind →] lemma prefixUntil [DecidableEq α] (G : SimpleDiGraph α)
    {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) (v : α) (h : v ∈ w.val) :
    G.IsSimpleWalkIn (w.prefixUntil v h) :=
  IsVertexSeqIn.prefixUntil G hw v h

/-- Taking a suffix of a realized walk preserves realization. -/
@[grind →] lemma suffixFrom [DecidableEq α] (G : SimpleDiGraph α)
    {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) (v : α) (h : v ∈ w.val) :
    G.IsSimpleWalkIn (w.suffixFrom v h) :=
  IsVertexSeqIn.suffixFrom G hw v h

/-- Taking the longest prefix on which `p` holds (plus its first failure)
preserves realization. -/
lemma takeWhile (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) (p : α → Prop) [DecidablePred p] :
    G.IsSimpleWalkIn (w.takeWhile p) :=
  IsVertexSeqIn.takeWhile G hw p

/-- Dropping the longest prefix on which `p` holds preserves realization. -/
lemma dropWhile (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) (p : α → Prop) [DecidablePred p]
    (h : ∃ v ∈ w.val.toList, ¬ p v) :
    G.IsSimpleWalkIn (w.dropWhile p h) :=
  IsVertexSeqIn.dropWhile G hw p h

/-- Loop erasure preserves realization. On a simple walk this operation is the
identity on the underlying sequence. -/
lemma loopErase [DecidableEq α] (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn (w.loopErase) :=
  IsVertexSeqIn.loopErase G hw

/-- Cycle erasure preserves realization. -/
lemma cycleErase [DecidableEq α] (G : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn (w.cycleErase) :=
  IsVertexSeqIn.cycleErase G hw

/-- Realization is monotone under passing to a supergraph. -/
@[grind →] lemma mono (G H : SimpleDiGraph α) {w : SimpleWalk α}
    (hw : H.IsSimpleWalkIn w) (hsub : H ≤ G) :
    G.IsSimpleWalkIn w :=
  IsVertexSeqIn.mono G H hw hsub

/-- If `G` has no arcs, every realized walk in `G` has length zero. -/
lemma length_zero_of_no_edges (G : SimpleDiGraph α) (hE : E(G) = ∅)
    {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) : w.length = 0 :=
  IsVertexSeqIn.length_zero_of_no_edges G hE hw

/-! ## Joining walks -/

/-- Appending two realized walks along an arc of `G` preserves realization. -/
lemma append (G : SimpleDiGraph α) {p q : SimpleWalk α}
    (hp : G.IsSimpleWalkIn p) (hq : G.IsSimpleWalkIn q)
    (ha : G.Adj p.tail q.head) :
    G.IsSimpleWalkIn (p.append q ha.ne) :=
  IsVertexSeqIn.append G hp hq ha

/-- Gluing two realized walks at a shared endpoint preserves realization. -/
lemma glue (G : SimpleDiGraph α) {p q : SimpleWalk α}
    (hp : G.IsSimpleWalkIn p) (hq : G.IsSimpleWalkIn q)
    (h : p.tail = q.head) :
    G.IsSimpleWalkIn (p.glue q h) := by
  unfold SimpleWalk.glue
  by_cases hlen : p.val.length = 0
  · rw [dif_pos hlen]
    exact hq
  · rw [dif_neg hlen]
    exact IsVertexSeqIn.append G (IsVertexSeqIn.dropTail G hp) hq
      (by
        have h' : p.val.tail = q.val.head := h
        rw [← h']
        exact IsVertexSeqIn.last_adj G hp hlen)

end IsSimpleWalkIn

end SimpleDiGraph

end GraphLib
