/-
Copyright (c) 2026 Basil Rohner. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Basil Rohner, Sorrachai Yingchareonthawornchai, Weixuan Yuan
-/
import GraphLib.Walk.InSimpleGraph.VertexSeq
import GraphLib.Walk.SimpleWalk

/-!
# Simple walks realized in a simple graph

`SimpleGraph.IsSimpleWalkIn G w` says a `SimpleWalk` is realized in `G` through
its underlying vertex sequence. This file lifts the `IsVertexSeqIn` API to
`SimpleWalk`, adds the edge-set / generated-subgraph bridge, and closure under
the walk operations (`append`, `glue`, `prefixUntil`, …).

Part of the `InSimpleGraph` folder; see the umbrella module
`GraphLib.Walk.InSimpleGraph`.
-/

variable {α γ : Type*}

namespace GraphLib

open scoped GraphLib

namespace SimpleGraph

/-! ## Simple walks realized in a graph -/

/-- A simple walk is realized in `G` when its underlying vertex sequence is
realized in `G`. -/
@[grind] def IsSimpleWalkIn (G : SimpleGraph α) (w : SimpleWalk α) : Prop :=
  G.IsVertexSeqIn w.val

namespace IsSimpleWalkIn

/-! ## Bridge to `IsVertexSeqIn` -/

/-- Realization of a simple walk is realization of its underlying vertex
sequence. -/
@[simp, grind =] lemma iff_isVertexSeqIn (G : SimpleGraph α) (w : SimpleWalk α) :
    G.IsSimpleWalkIn w ↔ G.IsVertexSeqIn w.val := Iff.rfl

/-! ## Vertex and edge membership -/

/-- The head of a realized walk is a vertex of `G`. -/
@[grind →] lemma head_mem (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : w.head ∈ V(G) :=
  IsVertexSeqIn.head_mem G hw

/-- The tail of a realized walk is a vertex of `G`. -/
@[grind →] lemma tail_mem (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : w.tail ∈ V(G) :=
  IsVertexSeqIn.tail_mem G hw

/-- Every vertex visited by a realized walk is a vertex of `G`. -/
@[grind →] lemma mem_vertexSet (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) {v : α} (hv : v ∈ w.support) : v ∈ V(G) :=
  IsVertexSeqIn.mem_vertexSet G hw hv

/-- Any edge traversed by a realized walk is an edge of `G`. -/
@[grind →] lemma edge_mem (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) {e : Sym2 α} (he : e ∈ w.edges) : e ∈ E(G) :=
  IsVertexSeqIn.edge_mem G hw he

/-- A walk is realized in `G` exactly when its head is a vertex of `G` and every
edge it traverses is an edge of `G`. -/
theorem iff_edges (G : SimpleGraph α) (w : SimpleWalk α) :
    G.IsSimpleWalkIn w ↔ w.head ∈ V(G) ∧ ∀ e ∈ w.edges, e ∈ E(G) :=
  IsVertexSeqIn.iff_edges G w.val

/-- Realization depends only on the ambient vertex and edge sets. -/
theorem congr {G H : SimpleGraph α} {w : SimpleWalk α}
    (hV : V(G) = V(H)) (hE : E(G) = E(H)) :
    G.IsSimpleWalkIn w ↔ H.IsSimpleWalkIn w := by
  rw [iff_edges G w, iff_edges H w, hV, hE]

/-! ## Graph transformations -/

theorem induce_iff (G : SimpleGraph α) (S : Set α) (w : SimpleWalk α) :
    (G.induce S).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ v ∈ w.support, v ∈ S :=
  IsVertexSeqIn.induce_iff G S w.val

theorem restrictEdges_iff (G : SimpleGraph α) (F : Set (Sym2 α)) (w : SimpleWalk α) :
    (G.restrictEdges F).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ e ∈ w.edges, e ∈ F :=
  IsVertexSeqIn.restrictEdges_iff G F w.val

theorem deleteEdges_iff (G : SimpleGraph α) (F : Set (Sym2 α)) (w : SimpleWalk α) :
    (G.deleteEdges F).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ e ∈ w.edges, e ∉ F :=
  IsVertexSeqIn.deleteEdges_iff G F w.val

theorem deleteVerts_iff (G : SimpleGraph α) (S : Set α) (w : SimpleWalk α) :
    (G.deleteVerts S).IsSimpleWalkIn w ↔
      G.IsSimpleWalkIn w ∧ ∀ v ∈ w.support, v ∉ S :=
  IsVertexSeqIn.deleteVerts_iff G S w.val

theorem relabelVertices {G : SimpleGraph α} {w : SimpleWalk α} (f : α ≃ γ)
    (h : G.IsSimpleWalkIn w) :
    (G.relabelVertices f).IsSimpleWalkIn (SimpleWalk.map f f.injective w) :=
  IsVertexSeqIn.relabelVertices f h

/-! ## Traversed edges and the generated simple graph -/

/-- The simple graph generated by a realized simple walk is a subgraph of `G`. -/
lemma toSimpleGraph_le (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : w.toSimpleGraph ≤ G := by
  exact ⟨fun v hv => mem_vertexSet G hw (by simpa using hv),
    fun e he => edge_mem G hw (by simpa using he)⟩

/-- If the graph generated by a simple walk is a subgraph of `G`, then the walk
is realized in `G`. -/
lemma of_toSimpleGraph_le (G : SimpleGraph α) {w : SimpleWalk α}
    (hsub : w.toSimpleGraph ≤ G) : G.IsSimpleWalkIn w := by
  rw [iff_edges]
  exact ⟨hsub.vertexSet_subset (by simp [SimpleWalk.support]),
    fun e he => hsub.edgeSet_subset (by simpa using he)⟩

/-- A simple walk is realized in `G` exactly when its generated simple graph is
a subgraph of `G`. -/
theorem iff_toSimpleGraph_le (G : SimpleGraph α) (w : SimpleWalk α) :
    G.IsSimpleWalkIn w ↔ w.toSimpleGraph ≤ G :=
  ⟨toSimpleGraph_le G, of_toSimpleGraph_le G⟩

/-! ## Closure under walk operations -/

/-- Reversing a realized walk preserves realization. -/
@[grind →] lemma reverse (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn w.reverse :=
  IsVertexSeqIn.reverse G hw

/-- Dropping the last vertex of a realized walk preserves realization. -/
@[grind →] lemma dropTail (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn w.dropTail :=
  IsVertexSeqIn.dropTail G hw

/-- Dropping the first vertex of a realized walk preserves realization. -/
@[grind →] lemma dropHead (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn w.dropHead :=
  IsVertexSeqIn.dropHead G hw

/-- Taking a prefix of a realized walk preserves realization. -/
@[grind →] lemma prefixUntil [DecidableEq α] (G : SimpleGraph α)
    {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) (v : α) (h : v ∈ w.val) :
    G.IsSimpleWalkIn (w.prefixUntil v h) :=
  IsVertexSeqIn.prefixUntil G hw v h

/-- Taking a suffix of a realized walk preserves realization. -/
@[grind →] lemma suffixFrom [DecidableEq α] (G : SimpleGraph α)
    {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) (v : α) (h : v ∈ w.val) :
    G.IsSimpleWalkIn (w.suffixFrom v h) :=
  IsVertexSeqIn.suffixFrom G hw v h

/-- Taking the longest prefix on which `p` holds (plus its first failure)
preserves realization. -/
lemma takeWhile (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) (p : α → Prop) [DecidablePred p] :
    G.IsSimpleWalkIn (w.takeWhile p) :=
  IsVertexSeqIn.takeWhile G hw p

/-- Dropping the longest prefix on which `p` holds preserves realization. -/
lemma dropWhile (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) (p : α → Prop) [DecidablePred p]
    (h : ∃ v ∈ w.val.toList, ¬ p v) :
    G.IsSimpleWalkIn (w.dropWhile p h) :=
  IsVertexSeqIn.dropWhile G hw p h

/-- Loop erasure preserves realization. On a simple walk this operation is the
identity on the underlying sequence. -/
lemma loopErase [DecidableEq α] (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn (w.loopErase) :=
  IsVertexSeqIn.loopErase G hw

/-- Cycle erasure preserves realization. -/
lemma cycleErase [DecidableEq α] (G : SimpleGraph α) {w : SimpleWalk α}
    (hw : G.IsSimpleWalkIn w) : G.IsSimpleWalkIn (w.cycleErase) :=
  IsVertexSeqIn.cycleErase G hw

/-! ## Joining walks -/

/-- Appending two realized walks along an edge of `G` preserves realization. -/
lemma append (G : SimpleGraph α) {p q : SimpleWalk α}
    (hp : G.IsSimpleWalkIn p) (hq : G.IsSimpleWalkIn q)
    (he : G.Adj p.tail q.head) :
    G.IsSimpleWalkIn (p.append q he.ne) :=
  IsVertexSeqIn.append G hp hq he

/-- Gluing two realized walks at a shared endpoint preserves realization. -/
lemma glue (G : SimpleGraph α) {p q : SimpleWalk α}
    (hp : G.IsSimpleWalkIn p) (hq : G.IsSimpleWalkIn q)
    (h : p.tail = q.head) :
    G.IsSimpleWalkIn (p.glue q h) := by
  unfold SimpleWalk.glue
  split
  · exact hq
  · rename_i hlen
    apply IsVertexSeqIn.append G (IsVertexSeqIn.dropTail G hp) hq
    simpa only [h] using IsVertexSeqIn.last_adj G hp hlen

/-! ## Monotonicity -/

/-- Realization is monotone under passing to a supergraph. -/
@[grind →] lemma mono (G H : SimpleGraph α) {w : SimpleWalk α}
    (hw : H.IsSimpleWalkIn w) (hsub : H ≤ G) :
    G.IsSimpleWalkIn w :=
  IsVertexSeqIn.mono G H hw hsub

/-! ## Edge-free graphs -/

/-- If `G` has no edges, every realized walk in `G` has length zero. -/
lemma length_zero_of_no_edges (G : SimpleGraph α) (hE : E(G) = ∅)
    {w : SimpleWalk α} (hw : G.IsSimpleWalkIn w) : w.length = 0 :=
  IsVertexSeqIn.length_zero_of_no_edges G hE hw

end IsSimpleWalkIn

end SimpleGraph

end GraphLib
