"""Signed frontend combinations, checked against the independent typed arithmetic oracle."""
import argparse
import itertools
from pathlib import Path
from generate import source, V, size
from reference import evaluate, self_test


def render():
    self_test()
    out = ['/-',
           'Copyright (c) 2026 Sorrachai Yingchareonthawornchai. All rights reserved.',
           'Released under Apache 2.0 license as described in the file LICENSE.',
           'Authors: Sorrachai Yingchareonthawornchai', '-/',
           'import AlgoLib.Experimental.RAM.Prototype.Composition.Assembly', '',
           '/-!\n# Signed differential frontend tests\n\nGenerated by generate_signed.py using the independent Python evaluator.\nNatural loop counters retain Nat arithmetic; int- nodes use signed subtraction.\n-/',
           'namespace AlgoLib.Experimental.RAM.Tests.Conformance.Signed',
           'open Prototype.Composition Prototype.Frontend', '',
           'ram method tick (mut x : Int) return (result : Int)',
           '  ensures result = xOld + 1', '  do', '    x := x + 1',
           'generate_obligations tick', 'complete_algorithm tick', '']
    inputs = [list(xs) for n in range(4) for xs in itertools.product((-3, 0, 2), repeat=n)]
    for number, (delta, nested) in enumerate(itertools.product((1, 3), (False, True))):
        update = [('if', ('<', V('x'), 0), [('call', 'x')],
                   [('assign', 'x', ('int-', V('x'), delta))]),
                  ('store', V('i'), ('int-', ('*', V('x'), 2), delta))]
        body = [('local', 'x', ('read', V('i')))]
        if nested:
            body += [('local', 'j', 0), ('while', 'inner', ('<', V('j'), 2),
                     ('j ≤ 2', 'i < arr.size', 'arr.size = arrOld.size'),
                     update + [('assign', 'j', ('+', V('j'), 1))])]
        else:
            body += update
        body += [('assign', 'i', ('+', V('i'), 1))]
        program = [('local', 'i', 0), ('while', 'outer', ('<', V('i'), size),
                   ('i ≤ arr.size', 'arr.size = arrOld.size'), body)]
        name = f'signed{number}'
        printed = [line.replace(' int- ', ' - ') for line in source(program)]
        out += [f'ram method {name} (mut arr : Array Int) return (result : Unit)',
                '  ensures True', '  do', *printed,
                f'generate_obligations {name}', f'complete_algorithm {name}',
                f'compile_array_method {name}', '', 'set_option linter.hashCommand false in',
                '#guard_msgs in', '#eval show IO Unit from do',
                '  let cases : List (List Int × List Int) := [']
        out += [',\n'.join(f'    ({xs}, {evaluate(program, xs)})' for xs in inputs) + ']',
                '  for (xs, expected) in cases do', f'    let actual := {name}Run xs',
                f'    unless actual.value == expected && actual.steps ≤ {name}Bound xs do',
                f'      throw <| IO.userError s!"{name}: {{xs}} -> {{actual.value}}, expected {{expected}}"', '']
    return '\n'.join(out + ['end AlgoLib.Experimental.RAM.Tests.Conformance.Signed', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = Path(__file__).with_name('Signed.lean')
    text = render()
    if args.check:
        if target.read_text() != text:
            raise SystemExit('Stale signed corpus: run generate_signed.py')
    else:
        target.write_text(text)
    print('Signed conformance: 4 programs, 160 independent input/output comparisons')
