/-
Copyright (c) 2026 Sorrachai Yingchareonthawornchai. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sorrachai Yingchareonthawornchai
-/
import AlgoLib.Experimental.RAM.Compiler.Assembly

/-!
# Signed differential frontend tests

Generated by generate_signed.py using the independent Python evaluator.
Natural loop counters retain Nat arithmetic; int- nodes use signed subtraction.
-/
namespace AlgoLib.Experimental.RAM.Tests.Conformance.Signed
open Prototype.Composition Prototype.Frontend

ram method tick (mut x : Int) return (result : Int)
  ensures result = xOld + 1
  do
    x := x + 1
generate_obligations tick
complete_algorithm tick

ram method signed0 (mut arr : Array Int) return (result : Unit)
  ensures True
  do
    let mut i := 0
    while (i < arr.size) named outer
      invariant "fact0" i ≤ arr.size
      invariant "fact1" arr.size = arrOld.size
      iterations_at_most arr.size - i
      do
        let mut x := arr[i]!
        if (x < 0) then
          x.tickProcedure()
        else
          x := (x - 1)
        arr[i] := ((x * 2) - 1)
        i := (i + 1)
generate_obligations signed0
complete_algorithm signed0
compile_array_method signed0

set_option linter.hashCommand false in
#guard_msgs in
#eval show IO Unit from do
  let cases : List (List Int × List Int) := [
    ([], []),
    ([-3], [-5]),
    ([0], [-3]),
    ([2], [1]),
    ([-3, -3], [-5, -5]),
    ([-3, 0], [-5, -3]),
    ([-3, 2], [-5, 1]),
    ([0, -3], [-3, -5]),
    ([0, 0], [-3, -3]),
    ([0, 2], [-3, 1]),
    ([2, -3], [1, -5]),
    ([2, 0], [1, -3]),
    ([2, 2], [1, 1]),
    ([-3, -3, -3], [-5, -5, -5]),
    ([-3, -3, 0], [-5, -5, -3]),
    ([-3, -3, 2], [-5, -5, 1]),
    ([-3, 0, -3], [-5, -3, -5]),
    ([-3, 0, 0], [-5, -3, -3]),
    ([-3, 0, 2], [-5, -3, 1]),
    ([-3, 2, -3], [-5, 1, -5]),
    ([-3, 2, 0], [-5, 1, -3]),
    ([-3, 2, 2], [-5, 1, 1]),
    ([0, -3, -3], [-3, -5, -5]),
    ([0, -3, 0], [-3, -5, -3]),
    ([0, -3, 2], [-3, -5, 1]),
    ([0, 0, -3], [-3, -3, -5]),
    ([0, 0, 0], [-3, -3, -3]),
    ([0, 0, 2], [-3, -3, 1]),
    ([0, 2, -3], [-3, 1, -5]),
    ([0, 2, 0], [-3, 1, -3]),
    ([0, 2, 2], [-3, 1, 1]),
    ([2, -3, -3], [1, -5, -5]),
    ([2, -3, 0], [1, -5, -3]),
    ([2, -3, 2], [1, -5, 1]),
    ([2, 0, -3], [1, -3, -5]),
    ([2, 0, 0], [1, -3, -3]),
    ([2, 0, 2], [1, -3, 1]),
    ([2, 2, -3], [1, 1, -5]),
    ([2, 2, 0], [1, 1, -3]),
    ([2, 2, 2], [1, 1, 1])]
  for (xs, expected) in cases do
    let actual := signed0Run xs
    unless actual.value == expected && actual.steps ≤ signed0Bound xs do
      throw <| IO.userError s!"signed0: {xs} -> {actual.value}, expected {expected}"

ram method signed1 (mut arr : Array Int) return (result : Unit)
  ensures True
  do
    let mut i := 0
    while (i < arr.size) named outer
      invariant "fact0" i ≤ arr.size
      invariant "fact1" arr.size = arrOld.size
      iterations_at_most arr.size - i
      do
        let mut x := arr[i]!
        let mut j := 0
        while (j < 2) named inner
          invariant "fact0" j ≤ 2
          invariant "fact1" i < arr.size
          invariant "fact2" arr.size = arrOld.size
          iterations_at_most 2 - j
          do
            if (x < 0) then
              x.tickProcedure()
            else
              x := (x - 1)
            arr[i] := ((x * 2) - 1)
            j := (j + 1)
        i := (i + 1)
generate_obligations signed1
complete_algorithm signed1
compile_array_method signed1

set_option linter.hashCommand false in
#guard_msgs in
#eval show IO Unit from do
  let cases : List (List Int × List Int) := [
    ([], []),
    ([-3], [-3]),
    ([0], [-1]),
    ([2], [-1]),
    ([-3, -3], [-3, -3]),
    ([-3, 0], [-3, -1]),
    ([-3, 2], [-3, -1]),
    ([0, -3], [-1, -3]),
    ([0, 0], [-1, -1]),
    ([0, 2], [-1, -1]),
    ([2, -3], [-1, -3]),
    ([2, 0], [-1, -1]),
    ([2, 2], [-1, -1]),
    ([-3, -3, -3], [-3, -3, -3]),
    ([-3, -3, 0], [-3, -3, -1]),
    ([-3, -3, 2], [-3, -3, -1]),
    ([-3, 0, -3], [-3, -1, -3]),
    ([-3, 0, 0], [-3, -1, -1]),
    ([-3, 0, 2], [-3, -1, -1]),
    ([-3, 2, -3], [-3, -1, -3]),
    ([-3, 2, 0], [-3, -1, -1]),
    ([-3, 2, 2], [-3, -1, -1]),
    ([0, -3, -3], [-1, -3, -3]),
    ([0, -3, 0], [-1, -3, -1]),
    ([0, -3, 2], [-1, -3, -1]),
    ([0, 0, -3], [-1, -1, -3]),
    ([0, 0, 0], [-1, -1, -1]),
    ([0, 0, 2], [-1, -1, -1]),
    ([0, 2, -3], [-1, -1, -3]),
    ([0, 2, 0], [-1, -1, -1]),
    ([0, 2, 2], [-1, -1, -1]),
    ([2, -3, -3], [-1, -3, -3]),
    ([2, -3, 0], [-1, -3, -1]),
    ([2, -3, 2], [-1, -3, -1]),
    ([2, 0, -3], [-1, -1, -3]),
    ([2, 0, 0], [-1, -1, -1]),
    ([2, 0, 2], [-1, -1, -1]),
    ([2, 2, -3], [-1, -1, -3]),
    ([2, 2, 0], [-1, -1, -1]),
    ([2, 2, 2], [-1, -1, -1])]
  for (xs, expected) in cases do
    let actual := signed1Run xs
    unless actual.value == expected && actual.steps ≤ signed1Bound xs do
      throw <| IO.userError s!"signed1: {xs} -> {actual.value}, expected {expected}"

ram method signed2 (mut arr : Array Int) return (result : Unit)
  ensures True
  do
    let mut i := 0
    while (i < arr.size) named outer
      invariant "fact0" i ≤ arr.size
      invariant "fact1" arr.size = arrOld.size
      iterations_at_most arr.size - i
      do
        let mut x := arr[i]!
        if (x < 0) then
          x.tickProcedure()
        else
          x := (x - 3)
        arr[i] := ((x * 2) - 3)
        i := (i + 1)
generate_obligations signed2
complete_algorithm signed2
compile_array_method signed2

set_option linter.hashCommand false in
#guard_msgs in
#eval show IO Unit from do
  let cases : List (List Int × List Int) := [
    ([], []),
    ([-3], [-7]),
    ([0], [-9]),
    ([2], [-5]),
    ([-3, -3], [-7, -7]),
    ([-3, 0], [-7, -9]),
    ([-3, 2], [-7, -5]),
    ([0, -3], [-9, -7]),
    ([0, 0], [-9, -9]),
    ([0, 2], [-9, -5]),
    ([2, -3], [-5, -7]),
    ([2, 0], [-5, -9]),
    ([2, 2], [-5, -5]),
    ([-3, -3, -3], [-7, -7, -7]),
    ([-3, -3, 0], [-7, -7, -9]),
    ([-3, -3, 2], [-7, -7, -5]),
    ([-3, 0, -3], [-7, -9, -7]),
    ([-3, 0, 0], [-7, -9, -9]),
    ([-3, 0, 2], [-7, -9, -5]),
    ([-3, 2, -3], [-7, -5, -7]),
    ([-3, 2, 0], [-7, -5, -9]),
    ([-3, 2, 2], [-7, -5, -5]),
    ([0, -3, -3], [-9, -7, -7]),
    ([0, -3, 0], [-9, -7, -9]),
    ([0, -3, 2], [-9, -7, -5]),
    ([0, 0, -3], [-9, -9, -7]),
    ([0, 0, 0], [-9, -9, -9]),
    ([0, 0, 2], [-9, -9, -5]),
    ([0, 2, -3], [-9, -5, -7]),
    ([0, 2, 0], [-9, -5, -9]),
    ([0, 2, 2], [-9, -5, -5]),
    ([2, -3, -3], [-5, -7, -7]),
    ([2, -3, 0], [-5, -7, -9]),
    ([2, -3, 2], [-5, -7, -5]),
    ([2, 0, -3], [-5, -9, -7]),
    ([2, 0, 0], [-5, -9, -9]),
    ([2, 0, 2], [-5, -9, -5]),
    ([2, 2, -3], [-5, -5, -7]),
    ([2, 2, 0], [-5, -5, -9]),
    ([2, 2, 2], [-5, -5, -5])]
  for (xs, expected) in cases do
    let actual := signed2Run xs
    unless actual.value == expected && actual.steps ≤ signed2Bound xs do
      throw <| IO.userError s!"signed2: {xs} -> {actual.value}, expected {expected}"

ram method signed3 (mut arr : Array Int) return (result : Unit)
  ensures True
  do
    let mut i := 0
    while (i < arr.size) named outer
      invariant "fact0" i ≤ arr.size
      invariant "fact1" arr.size = arrOld.size
      iterations_at_most arr.size - i
      do
        let mut x := arr[i]!
        let mut j := 0
        while (j < 2) named inner
          invariant "fact0" j ≤ 2
          invariant "fact1" i < arr.size
          invariant "fact2" arr.size = arrOld.size
          iterations_at_most 2 - j
          do
            if (x < 0) then
              x.tickProcedure()
            else
              x := (x - 3)
            arr[i] := ((x * 2) - 3)
            j := (j + 1)
        i := (i + 1)
generate_obligations signed3
complete_algorithm signed3
compile_array_method signed3

set_option linter.hashCommand false in
#guard_msgs in
#eval show IO Unit from do
  let cases : List (List Int × List Int) := [
    ([], []),
    ([-3], [-5]),
    ([0], [-7]),
    ([2], [-3]),
    ([-3, -3], [-5, -5]),
    ([-3, 0], [-5, -7]),
    ([-3, 2], [-5, -3]),
    ([0, -3], [-7, -5]),
    ([0, 0], [-7, -7]),
    ([0, 2], [-7, -3]),
    ([2, -3], [-3, -5]),
    ([2, 0], [-3, -7]),
    ([2, 2], [-3, -3]),
    ([-3, -3, -3], [-5, -5, -5]),
    ([-3, -3, 0], [-5, -5, -7]),
    ([-3, -3, 2], [-5, -5, -3]),
    ([-3, 0, -3], [-5, -7, -5]),
    ([-3, 0, 0], [-5, -7, -7]),
    ([-3, 0, 2], [-5, -7, -3]),
    ([-3, 2, -3], [-5, -3, -5]),
    ([-3, 2, 0], [-5, -3, -7]),
    ([-3, 2, 2], [-5, -3, -3]),
    ([0, -3, -3], [-7, -5, -5]),
    ([0, -3, 0], [-7, -5, -7]),
    ([0, -3, 2], [-7, -5, -3]),
    ([0, 0, -3], [-7, -7, -5]),
    ([0, 0, 0], [-7, -7, -7]),
    ([0, 0, 2], [-7, -7, -3]),
    ([0, 2, -3], [-7, -3, -5]),
    ([0, 2, 0], [-7, -3, -7]),
    ([0, 2, 2], [-7, -3, -3]),
    ([2, -3, -3], [-3, -5, -5]),
    ([2, -3, 0], [-3, -5, -7]),
    ([2, -3, 2], [-3, -5, -3]),
    ([2, 0, -3], [-3, -7, -5]),
    ([2, 0, 0], [-3, -7, -7]),
    ([2, 0, 2], [-3, -7, -3]),
    ([2, 2, -3], [-3, -3, -5]),
    ([2, 2, 0], [-3, -3, -7]),
    ([2, 2, 2], [-3, -3, -3])]
  for (xs, expected) in cases do
    let actual := signed3Run xs
    unless actual.value == expected && actual.steps ≤ signed3Bound xs do
      throw <| IO.userError s!"signed3: {xs} -> {actual.value}, expected {expected}"

end AlgoLib.Experimental.RAM.Tests.Conformance.Signed
